# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8dbee0d57d28c1776919751a764c2dfaee71a75b68ebc978a1c3a71ffba75c22da9e31825c74e32beb9188a831cdd6ff37f448d3f3688086b718e65d3c4ba4bc

test:
  secret_key_base: b5082902f334c2233f212f23219b68f97f875999d226efaddafd97a6d21b13e542a2e78aebb03f25728df8a3df96253bd7aba9d393a47c94d703e3eb773ac2a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
